# 选择的网口名称
interface=wlp8s0
# 线驱动，一般有两种：wext/nl80211，wext版本较旧目前一般使用nl80211
driver=nl80211
# iEEE802.11n
ieee80211n=1
# 802.11g,一般三个模式: a,b,g。a->5GHZ,g->2.4GHZ, 如果网卡支持，尝试改为 hw_mode=a
hw_mode=g
# wifi工作的信道，2.4GHZ(1~14),建议使用1、6、11这三个不重叠的信道
channel=3
# 如果网卡支持5GHz，可以启用更宽的频宽：
# ieee80211n=1
# ieee80211ac=1
# vht_oper_chwidth=1
# vht_oper_centr_freq_seg0_idx=42

# 之前设置0，网络很慢
wmm_enabled=1

ignore_broadcast_ssid=0
# AP的名称，类似于我们的路由器名称
ssid=ZL-L755-Local
# 选择加密方式为WPA2,常用加解密方法是有WEP、WPA、WPA2、WPA3
wpa=2
# 密码
wpa_passphrase=jiushi123
# 加密方式
wpa_key_mgmt=WPA-PSK
# 加密算法, 只使用CCMP，移除TKIP，之前网络很慢
rsn_pairwise=CCMP
# 添加性能优化参数
require_ht=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]
country_code=CN
